### PR TITLE
Added upgrade notice in README.md

### PR DESCRIPTION
**Pull request by vidarl**

### CODE REVIEW

**Review by andrerom — APPROVED** [review]

**Comment by DominikaK** [comment]
@vidarl, this repo is maintained only for the versions of the tutorial still within service life (which 2.2 isn't). This information should be placed in the migration guide in the main doc.

**Comment by vidarl** [comment]
I am currently working a PR for doc too. My plan was to link to this `upgraded_to_2.2` branch as an example on how to do this

**Comment by DominikaK** [comment]
Please let's not keep examples here that are not strictly related to the tutorial as described in the doc.
If you need a good place to store examples, we'll figure something out once your doc PR is ready.

**Comment by DominikaK** [comment]
Covered in https://github.com/ezsystems/developer-documentation/pull/984

**Pull request closed without merging**
